### ISSUE TITLE
ValueError: No objects to concatenate, minimum_pairwise_distance.csv is empty 

### ISSUE THREAD

**Issue by abrantesas** [McIntyre-Lab/TranD#3]
Hello, 
I have taken a SQANTI generated transcriptome and split into case and control gffs.
I installed TranD with the pip method and run with syntax as shown in the github tutorial .
Here is how it was called:
trand -o /nas/depts/007/sullilab/shared/longread_2020/03analysis/TranD -1 control -2 schizophrenia \
	-p both -f -n 4 \
	/nas/depts/007/sullilab/shared/longread_2020/01data/TranD/control.gff /nas/depts/007/sullilab/shared/longread_2020/01data/TranD/scz.gff 

It looks like the complexity files (png, rtf, csv) are created and the gtf1 and gtf2_only.gtf files are there. All other output is missing or the file is empty except a header.
Any advice on what to do about this error is appreciated. 
Thanks, Anthony
Below is the error output:

Traceback (most recent call last):
  File "/nas/longleaf/home/abrantes/anaconda3/envs/TranD/bin/trand", line 8, in <module>
    sys.exit(cli())
  File "/nas/longleaf/home/abrantes/anaconda3/envs/TranD/lib/python3.8/site-packages/trand/main.py", line 340, in cli
    process_two_files(
  File "/nas/longleaf/home/abrantes/anaconda3/envs/TranD/lib/python3.8/site-packages/trand/event_analysis.py", line 1408, in process_two_files
    ea_cat = pd.concat(ea_list, ignore_index=True)
  File "/nas/longleaf/home/abrantes/anaconda3/envs/TranD/lib/python3.8/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/nas/longleaf/home/abrantes/anaconda3/envs/TranD/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 368, in concat
    op = _Concatenator(
  File "/nas/longleaf/home/abrantes/anaconda3/envs/TranD/lib/python3.8/site-packages/pandas/core/reshape/concat.py", line 425, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

**Comment by avnanni** [comment]
Hello Anthony,

We have updated the PyPi package. Please try updating the TranD package with pip and see if this resolves the error you are receiving.

Thank you,
Adalena Nanni

**Comment by abrantesas** [comment]
I will give it a try and let you know. I just installed last Friday, when was the package updated?

**Comment by avnanni** [comment]
The package was just updated a few minutes prior to my first comment so hopefully this will fix the issue you are having.

**Comment by abrantesas** [comment]
Hi, I believe it is working since I no longer get the error but I haven't got the analysis to complete yet. I am using 8 CPUs and 128GB RAM and it didn't finish in the 12 hours I gave it to run. The gtfs are about 450MB each. Do you think if I up the time or RAM it will finish or should I just filter the gtfs down to a smaller size?

**Comment by avnanni** [comment]
I am glad the error has been resolved. As for the time/memory requirements, we are currently working on benchmarking the tool to be able to estimate those requirements prior to running. These are dependent on the number of transcript pairs present between the two GTF files. Could you download and run the utility python script below that we have created to take in two gtf files and calculate general statistics, including the number of pairs, and send me the output you receive from this. I can then give you a more accurate estimate of time and memory based on our benchmarking so far.

Script: https://github.com/McIntyre-Lab/TranD/blob/gtf_simple_stats/utilities/gtf_simple_stats_01gwv.py

Usage: (within TranD conda environment) python gtf_simple_stats_01gwv.py --gtf1 /path/to/first_gtf.gtf --gtf2 /path/to/second_gtf.gtf -o /path/to/output_stats.csv

**Comment by abrantesas** [comment]
[output_stats.csv](https://github.com/McIntyre-Lab/TranD/files/11006741/output_stats.csv)

**Comment by avnanni** [comment]
Dear Anthony,

Based on our current estimates and the large number of pairs you have, I would first recommend to perform a consolidation on your data (trand has a splice-match consolidation function that can be used on each GTF individually, see example in User Guide here: https://github.com/McIntyre-Lab/TranD/wiki/User-Guide#transcriptome-consolidation)

Once your GTF files have been consolidated, I also recommend splitting your GTF files by chromosome and run each chromosome separately. The memory you are providing should be sufficient for each chromosome. Depending on the amount of consolidation, you may need to provide each run with several days to run. If you have the ability to use more CPUs it would greatly increase the efficiency of the run.

If you would like to run the gtf_simple_stats python script on each consolidated GTF split by chromosome, you can provide me with the output for each (in this case the usage would be --gtf1 /path/to/consolidated_first_gtf_chr1.gtf --gtf2 /path/to/consolidated_second_gtf_chr1.gtf -o /path/to/output_stats_chr1.csv). I can then give you more accurate estimates of runtime for each chromosome.

Please let me know if you have any questions about the above suggestions.

**Comment by abrantesas** [comment]
It took a little over 2 hours to complete chr21.

**Comment by avnanni** [comment]
I'm glad your smaller chromosome was able to finish. I think that even with splitting my chromosome, your larger chromosomes are going to take quite a long time with so many pairs.

My next recommendation is to try running 1GTF **gene mode** on each of these (so 2 runs per chromosome since there are two samples). This will run faster than the pairwise and can give you some indication of the complexity of each of those transcriptomes so that maybe you can remove some genes that have too many transcripts to be processed in a reasonable amount of time.

**Comment by abrantesas** [comment]
I tried to run them all and only the 3 smallest chromosomes finished in a day. I think I will use the benchmark tool and filter by counts until I get them small enough to run in pair mode. Thanks for the help!
